version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3E*
      - TZ=Asia/Shanghai
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW

  canal:
    image: canal/canal-server
    container_name: canal
    ports:
      - "11111:11111"
    environment:
      - canal.instance.master.address=192.168.31.43:3306
      - canal.instance.mysql.slaveId=2 # canal的slaveId，需要唯一 不要和mysql的slaveId重复
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=1q2w3E*
    depends_on:
      - mysql
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
